import { Role } from './types';

export const ROLES: Role[] = [
  {
    id: 'guojing',
    name: '郭靖',
    title: '店店长/总指挥',
    responsibility: '整体运营策略、目标制定、最终决策',
    tasks: ['销售目标', '库存策略', '定价决策'],
    color: 'bg-red-900',
    avatar: '🏹',
    motto: '侠之大者，为国为民；店之大者，保质保量。',
    specialSkill: '降龙十八掌 · 稳扎稳打',
    pattern: 'radial-gradient(circle at 2px 2px, rgba(225,29,72,0.1) 1px, transparent 0)',
    stats: [
      { label: '本月GMV目标', value: '¥2,400,000', trend: 'up' },
      { label: '库存周转率', value: '12.5次/年', trend: 'neutral' },
    ],
  },
  {
    id: 'huangrong',
    name: '黄蓉',
    title: '营销策划',
    responsibility: '营销方案、活动策划、内容创作',
    tasks: ['详情页文案', '朋友圈素材', '促销方案'],
    color: 'bg-emerald-800',
    avatar: '🎋',
    motto: '算无遗策，妙笔生花。',
    specialSkill: '打狗棒法 · 变幻莫测',
    pattern: 'linear-gradient(45deg, rgba(16,185,129,0.05) 25%, transparent 25%, transparent 50%, rgba(16,185,129,0.05) 50%, rgba(16,185,129,0.05) 75%, transparent 75%, transparent)',
    stats: [
      { label: '活动转化率', value: '4.8%', trend: 'up' },
      { label: '素材产出量', value: '42份/周', trend: 'up' },
    ],
  },
  {
    id: 'yangguo',
    name: '杨过',
    title: '销售主力',
    responsibility: '客户咨询、订单跟进、转化促成',
    tasks: ['回复咨询', '推荐产品', '处理议价'],
    color: 'bg-slate-700',
    avatar: '🦅',
    motto: '重剑无锋，大巧不工；销售无痕，成交有道。',
    specialSkill: '黯然销魂掌 · 绝处逢生',
    pattern: 'repeating-linear-gradient(0deg, transparent, transparent 20px, rgba(148,163,184,0.05) 20px, rgba(148,163,184,0.05) 21px)',
    stats: [
      { label: '询单转化率', value: '68%', trend: 'up' },
      { label: '平均响应时间', value: '15秒', trend: 'down' },
    ],
  },
  {
    id: 'xiaolongnu',
    name: '小龙女',
    title: '品控/售后',
    responsibility: '质量把关、售后处理、评价管理',
    tasks: ['处理退换货', '回复评价', '质量反馈'],
    color: 'bg-blue-100 text-blue-900',
    avatar: '🦢',
    motto: '清冷自持，不容瑕疵。',
    specialSkill: '玉女心经 · 细致入微',
    pattern: 'radial-gradient(rgba(59,130,246,0.1) 1px, transparent 0)',
    stats: [
      { label: '好评率', value: '99.8%', trend: 'neutral' },
      { label: '退货率', value: '0.5%', trend: 'down' },
    ],
  },
  {
    id: 'zhoubotong',
    name: '周伯通',
    title: '市场调研',
    responsibility: '竞品分析、价格监控、趋势研究',
    tasks: ['淘宝/京东比价', '新品发现', '卖点提炼'],
    color: 'bg-amber-600',
    avatar: '🐝',
    motto: '左右互搏，洞悉天下。',
    specialSkill: '空明拳 · 以虚御实',
    pattern: 'linear-gradient(90deg, rgba(245,158,11,0.05) 1px, transparent 0)',
    stats: [
      { label: '竞品监控数', value: '120个', trend: 'up' },
      { label: '趋势预测准确度', value: '85%', trend: 'up' },
    ],
  },
  {
    id: 'ouyangfeng',
    name: '欧阳锋',
    title: '财务/风控',
    responsibility: '成本核算、利润分析、风险控制',
    tasks: ['成本计算', '利润报表', '防骗预警'],
    color: 'bg-purple-900',
    avatar: '🐍',
    motto: '逆练真经，反向控本。',
    specialSkill: '蛤蟆功 · 蓄势待发',
    pattern: 'repeating-radial-gradient(circle at 0 0, transparent, transparent 40px, rgba(168,85,247,0.05) 40px, rgba(168,85,247,0.05) 41px)',
    stats: [
      { label: '净利润率', value: '22%', trend: 'up' },
      { label: '异常订单拦截', value: '15笔', trend: 'neutral' },
    ],
  },
  {
    id: 'hongqigong',
    name: '洪七公',
    title: '物流/交付',
    responsibility: '发货安排、物流跟踪、仓库管理',
    tasks: ['打单发货', '库存同步', '物流异常处理'],
    color: 'bg-orange-800',
    avatar: '🍗',
    motto: '降龙十八掌，掌掌发货快。',
    specialSkill: '逍遥游 · 瞬息千里',
    pattern: 'linear-gradient(rgba(234,88,12,0.05) 2px, transparent 2px)',
    stats: [
      { label: '24h发货率', value: '98.5%', trend: 'up' },
      { label: '物流投诉率', value: '0.1%', trend: 'down' },
    ],
  },
];
